version: '3.8'

services:
  remote-docker-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remote-docker-manager
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - TZ=Asia/Baku
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - docker-manager-network

networks:
  docker-manager-network:
    driver: bridge